name: Cache Hit Please

description: |
  Managed `actions/cache` with segmented cache keys and more outputs.

runs:
  using: "node20"
  main: "dist/main.js"
  post: "dist/post.js"

inputs:
  deps:
    required: true
    description: |
      Dependencies of the cache, as a list of strings/hashes, ordered from the
      most stable to the most variable.

  path:
    required: true
    description: |
      Paths to cache.

outputs:
  primary-key:
    description: |
      The calculated cache key.

  restore-key:
    description: |
      The calculated list of restore keys.

  cache-hit:
    description: |
      A boolean value to indicate an exact match was found for the key.

  path:
    description: |
      The original `path` parameter.
